/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2018-07-24 12:10:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"BIG5\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tfont-size: 0.25in;\r\n");
      out.write("\t\tfont-family: Arial;\r\n");
      out.write("\t\tbackground: linear-gradient(#369, #222);;\r\n");
      out.write("\t\t/*background-image: url(\"https://fsa.zobj.net/crop.php?r=ao88GxCisk4oY2NINS9REEtIWhpZOc22-qItDMLD3PM32O_JkS6wNJkg6nyYIREcmC0vWqaqI6LJaUOxd-WXbPJcJwdQ8BFboZ63vqok2a4Dr1BmLINjzf1ENB44EzZlDTbMtV754atZi7iy\");*/\r\n");
      out.write("\t\t/*background-size: cover;*/\r\n");
      out.write("\t}\r\n");
      out.write("\th1{\r\n");
      out.write("\t\tcolor: #FFF;\r\n");
      out.write("\t\ttext-shadow: 0px 2px 5px #000;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\th2{\r\n");
      out.write("\t\tcolor: #F80;\r\n");
      out.write("\t\ttext-shadow: 0px 2px 5px #000;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\torange{\r\n");
      out.write("\t\tcolor: #F80;\r\n");
      out.write("\t\tfont-size: 0.5in;\r\n");
      out.write("\t\tmargin-right: 0.25in;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable{\t\t\r\n");
      out.write("\t\twidth: 80%;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\tborder-spacing: 0.15in;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd{\r\n");
      out.write("\t\tcolor: #FFF;\r\n");
      out.write("\t\ttext-shadow: 0px 0px 3px #000;\r\n");
      out.write("\t\tpadding: 0.2in;\t\t\r\n");
      out.write("\t\tbackground: rgba(255,255,255,0.20);\t\t\r\n");
      out.write("\t\tbox-shadow: 0px 2px 10px #000;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd:first-child{\r\n");
      out.write("\t\twidth: 20%;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd:nth-child(2){\r\n");
      out.write("\t\twidth: 40%;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd:nth-child(3){\r\n");
      out.write("\t\twidth: 40%;\r\n");
      out.write("\t}\r\n");
      out.write("\ta:link\t\t{color: #47F;}\r\n");
      out.write("\ta:visited\t{color: #47F;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<h1>Java Web Code</h1><h2>2018/7/12~9/4</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

					String topic[][]={
						{"1","Servlet*, JSP*"},
						{"2","ServletContext, Filter, Expression Language(EL)"},
						{"3","Request, Response, Annotation, JSTL"},
						{"1","Servlet*, JSP*"},
						{"1","Servlet*, JSP*"},
						{"1","Servlet*, JSP*"},
						{"1","Servlet*, JSP*"},
						{"1","Servlet*, JSP*"},
						{"1","Servlet*, JSP*"},
					};
					
					
					
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t1, Servlet*, JSP*<br>\r\n");
      out.write("\t\t\t\t\t2, ServletContext, Filter, Expression Language(EL)<br>\r\n");
      out.write("\t\t\t\t\t3, Request, Response, Annotation, JSTL<br>\r\n");
      out.write("\t\t\t\t\t4, RequestDispatcher, JavaBean<br>\r\n");
      out.write("\t\t\t\t\t5, Session, Cookie, Tomcat, TLD<br>\r\n");
      out.write("\t\t\t\t\t6, Asynchronous Request, TLD<br>\r\n");
      out.write("\t\t\t\t\t7, Listener<br>\r\n");
      out.write("\t\t\t\t\t8, Deployment, Security<br>\r\n");
      out.write("\t\t\t\t\t0, Database\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>9</orange> 9/4</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>8</orange> 8/28, 8/30</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>7</orange> 8/21, 8/23</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>6</orange> 8/14, 8/16</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>5</orange> 8/7, 8/9</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>4</orange> 7/31, 8/2</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>3</orange> 7/24, 7/26</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\tServlet:\r\n");
      out.write("\t\t\t\t\t<a href=\"S311\">S311</a>,\r\n");
      out.write("\t\t\t\t\t<a href=\"S312\">S312</a>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tJSP/JSTL:\r\n");
      out.write("\t\t\t\t\t<a href=\"j311.jsp\">j311</a>,\r\n");
      out.write("\t\t\t\t\t<a href=\"j312.jsp\">j312</a>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tEL:\r\n");
      out.write("\t\t\t\t\t<a href=\"j313.jsp\">j313</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>2</orange> 7/17, 7/19</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<font color=\"#F40\">No trigger, Listener/Filter(F211)</font>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tServlet:\r\n");
      out.write("\t\t\t\t\t<a href=\"S211\">S211</a>,\r\n");
      out.write("\t\t\t\t\t<a href=\"S212\">S212</a>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tEL:\r\n");
      out.write("\t\t\t\t\t<a href=\"j211.jsp\">j211</a>,\r\n");
      out.write("\t\t\t\t\t<a href=\"j212.jsp\">j212</a>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tJSP:\r\n");
      out.write("\t\t\t\t\t<a href=\"j213.jsp\">j213</a>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\tServlet:\r\n");
      out.write("\t\t\t\t\t<a href=\"S221\">S221</a>,\r\n");
      out.write("\t\t\t\t\tS222,\r\n");
      out.write("\t\t\t\t\tS223,\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tJSP:\r\n");
      out.write("\t\t\t\t\t<a href=\"j221.jsp\">j221</a>,\r\n");
      out.write("\t\t\t\t\t<a href=\"j222.jsp\">j222</a>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tEL:\r\n");
      out.write("\t\t\t\t\t<a href=\"j223.jsp\">j223</a>\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><orange>1</orange> 7/14</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\tServlet:\r\n");
      out.write("\t\t\t\t\t<a href=\"S121\">S121</a>,\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tJSP:\r\n");
      out.write("\t\t\t\t\t<a href=\"j121.jsp\">j121</a>,\r\n");
      out.write("\t\t\t\t\t<a href=\"j122.jsp\">j122</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
